# Generated by Django 6.0.6 on 2026-06-29 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='??')),
                ('author', models.CharField(max_length=100, verbose_name='??')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='???')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('total_quantity', models.IntegerField(default=1, verbose_name='???')),
                ('available_quantity', models.IntegerField(default=1, verbose_name='????')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='????')),
                ('description', models.TextField(blank=True, verbose_name='??')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='????')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='????')),
            ],
            options={
                'verbose_name': '??',
                'verbose_name_plural': '??',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True, verbose_name='????')),
                ('due_date', models.DateTimeField(verbose_name='????')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='????')),
                ('status', models.CharField(choices=[('borrowed', '???'), ('returned', '???'), ('overdue', '??')], default='borrowed', max_length=20, verbose_name='??')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.book', verbose_name='??')),
                ('student', models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='??')),
            ],
            options={
                'verbose_name': '????',
                'verbose_name_plural': '????',
                'ordering': ['-borrow_date'],
            },
        ),
    ]
